
// This file has been generated by the GUI designer. Do not modify.
namespace TXM.Lin
{
	public partial class BeamerWindow
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.NodeView DataGridOutput;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TXM.Lin.BeamerWindow
			this.Name = "TXM.Lin.BeamerWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("BeamerWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child TXM.Lin.BeamerWindow.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.DataGridOutput = new global::Gtk.NodeView ();
			this.DataGridOutput.CanFocus = true;
			this.DataGridOutput.Name = "DataGridOutput";
			this.GtkScrolledWindow.Add (this.DataGridOutput);
			this.Add (this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 596;
			this.DefaultHeight = 484;
			this.Show ();
		}
	}
}
