
// This file has been generated by the GUI designer. Do not modify.
namespace TXM.Lin
{
	public partial class TableConverterWindow
	{
		private global::Gtk.VBox vbox8;
		
		private global::Gtk.Button ButtonConvert;
		
		private global::Gtk.Label LabelInput;
		
		private global::Gtk.HBox hbox15;
		
		private global::Gtk.Label label20;
		
		private global::Gtk.Entry TextboxSeperator;
		
		private global::Gtk.Button button599;
		
		private global::Gtk.Label LabelOutput;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TXM.Lin.TableConverterWindow
			this.Name = "TXM.Lin.TableConverterWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("TableConverterWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child TXM.Lin.TableConverterWindow.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.ButtonConvert = new global::Gtk.Button ();
			this.ButtonConvert.CanFocus = true;
			this.ButtonConvert.Name = "ButtonConvert";
			this.ButtonConvert.UseUnderline = true;
			this.ButtonConvert.Label = global::Mono.Unix.Catalog.GetString ("Eingabedatei auswählen");
			this.vbox8.Add (this.ButtonConvert);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.ButtonConvert]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.LabelInput = new global::Gtk.Label ();
			this.LabelInput.Name = "LabelInput";
			this.vbox8.Add (this.LabelInput);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.LabelInput]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox ();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Trennzeichen");
			this.hbox15.Add (this.label20);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.label20]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.TextboxSeperator = new global::Gtk.Entry ();
			this.TextboxSeperator.CanFocus = true;
			this.TextboxSeperator.Name = "TextboxSeperator";
			this.TextboxSeperator.IsEditable = true;
			this.TextboxSeperator.InvisibleChar = '●';
			this.hbox15.Add (this.TextboxSeperator);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.TextboxSeperator]));
			w4.Position = 1;
			this.vbox8.Add (this.hbox15);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox15]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.button599 = new global::Gtk.Button ();
			this.button599.CanFocus = true;
			this.button599.Name = "button599";
			this.button599.UseUnderline = true;
			this.button599.Label = global::Mono.Unix.Catalog.GetString ("Konvertieren");
			this.vbox8.Add (this.button599);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.button599]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.LabelOutput = new global::Gtk.Label ();
			this.LabelOutput.Name = "LabelOutput";
			this.vbox8.Add (this.LabelOutput);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.LabelOutput]));
			w7.Position = 4;
			w7.Expand = false;
			w7.Fill = false;
			this.Add (this.vbox8);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 407;
			this.DefaultHeight = 192;
			this.Show ();
			this.ButtonConvert.Clicked += new global::System.EventHandler (this.Button_Click);
			this.button599.Clicked += new global::System.EventHandler (this.ButtonConvert_Click);
		}
	}
}
