
// This file has been generated by the GUI designer. Do not modify.
namespace TXM.Lin
{
	public partial class NewTournament2Dialog
	{
		private global::Gtk.Fixed fixed2;
		
		private global::Gtk.Fixed fixed3;
		
		private global::Gtk.Fixed fixed4;
		
		private global::Gtk.Fixed fixed5;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.ComboBox ComboBoxTournamentType;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.RadioButton RadioButtonNoCut;
		
		private global::Gtk.RadioButton RadioButtonTop8;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.RadioButton RadioButtonTop4;
		
		private global::Gtk.RadioButton RadioButtonTop16;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Entry TextboxName;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.SpinButton IntegerUpDownMaxSquad;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button ButtonOK;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TXM.Lin.NewTournament2Dialog
			this.Name = "TXM.Lin.NewTournament2Dialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child TXM.Lin.NewTournament2Dialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			w1.Add (this.fixed2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(w1 [this.fixed2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			w1.Add (this.fixed3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(w1 [this.fixed3]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.fixed4 = new global::Gtk.Fixed ();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			w1.Add (this.fixed4);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.fixed4]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.fixed5 = new global::Gtk.Fixed ();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			w1.Add (this.fixed5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1 [this.fixed5]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("1. Turnierform auswählen:");
			this.hbox2.Add (this.label7);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label7]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.ComboBoxTournamentType = global::Gtk.ComboBox.NewText ();
			this.ComboBoxTournamentType.Name = "ComboBoxTournamentType";
			this.hbox2.Add (this.ComboBoxTournamentType);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.ComboBoxTournamentType]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox4.Add (this.hbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("2. Mit oder ohne Cut?");
			this.hbox3.Add (this.label9);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label9]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.RadioButtonNoCut = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Kein Cut"));
			this.RadioButtonNoCut.CanFocus = true;
			this.RadioButtonNoCut.Name = "RadioButtonNoCut";
			this.RadioButtonNoCut.DrawIndicator = true;
			this.RadioButtonNoCut.UseUnderline = true;
			this.RadioButtonNoCut.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox5.Add (this.RadioButtonNoCut);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.RadioButtonNoCut]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.RadioButtonTop8 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Top 8"));
			this.RadioButtonTop8.CanFocus = true;
			this.RadioButtonTop8.Name = "RadioButtonTop8";
			this.RadioButtonTop8.DrawIndicator = true;
			this.RadioButtonTop8.UseUnderline = true;
			this.RadioButtonTop8.Group = this.RadioButtonNoCut.Group;
			this.vbox5.Add (this.RadioButtonTop8);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.RadioButtonTop8]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.hbox4.Add (this.vbox5);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox5]));
			w12.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.RadioButtonTop4 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Top 4"));
			this.RadioButtonTop4.CanFocus = true;
			this.RadioButtonTop4.Name = "RadioButtonTop4";
			this.RadioButtonTop4.DrawIndicator = true;
			this.RadioButtonTop4.UseUnderline = true;
			this.RadioButtonTop4.Group = this.RadioButtonNoCut.Group;
			this.vbox6.Add (this.RadioButtonTop4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.RadioButtonTop4]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.RadioButtonTop16 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Top 16"));
			this.RadioButtonTop16.CanFocus = true;
			this.RadioButtonTop16.Name = "RadioButtonTop16";
			this.RadioButtonTop16.DrawIndicator = true;
			this.RadioButtonTop16.UseUnderline = true;
			this.RadioButtonTop16.Group = this.RadioButtonNoCut.Group;
			this.vbox6.Add (this.RadioButtonTop16);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.RadioButtonTop16]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.hbox4.Add (this.vbox6);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox6]));
			w15.Position = 1;
			this.hbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hbox4]));
			w16.Position = 1;
			this.vbox4.Add (this.hbox3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox3]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("3. Turniername:");
			this.hbox5.Add (this.label10);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label10]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.TextboxName = new global::Gtk.Entry ();
			this.TextboxName.CanFocus = true;
			this.TextboxName.Name = "TextboxName";
			this.TextboxName.IsEditable = true;
			this.TextboxName.InvisibleChar = '●';
			this.hbox5.Add (this.TextboxName);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.TextboxName]));
			w19.Position = 1;
			this.vbox4.Add (this.hbox5);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox5]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("4. Maximale Squadgröße");
			this.hbox6.Add (this.label11);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label11]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.IntegerUpDownMaxSquad = new global::Gtk.SpinButton (0, 10000, 1);
			this.IntegerUpDownMaxSquad.CanFocus = true;
			this.IntegerUpDownMaxSquad.Name = "IntegerUpDownMaxSquad";
			this.IntegerUpDownMaxSquad.Adjustment.PageIncrement = 10;
			this.IntegerUpDownMaxSquad.ClimbRate = 1;
			this.IntegerUpDownMaxSquad.Numeric = true;
			this.hbox6.Add (this.IntegerUpDownMaxSquad);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.IntegerUpDownMaxSquad]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.vbox4.Add (this.hbox6);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox6]));
			w23.Position = 3;
			w23.Expand = false;
			w23.Fill = false;
			w1.Add (this.vbox4);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox4]));
			w24.Position = 4;
			w24.Expand = false;
			w24.Fill = false;
			// Internal child TXM.Lin.NewTournament2Dialog.ActionArea
			global::Gtk.HButtonBox w25 = this.ActionArea;
			w25.Name = "dialog1_ActionArea";
			w25.Spacing = 10;
			w25.BorderWidth = ((uint)(5));
			w25.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w26 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w25 [this.buttonCancel]));
			w26.Expand = false;
			w26.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.ButtonOK = new global::Gtk.Button ();
			this.ButtonOK.CanDefault = true;
			this.ButtonOK.CanFocus = true;
			this.ButtonOK.Name = "ButtonOK";
			this.ButtonOK.UseStock = true;
			this.ButtonOK.UseUnderline = true;
			this.ButtonOK.Label = "gtk-ok";
			this.AddActionWidget (this.ButtonOK, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w27 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w25 [this.ButtonOK]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 349;
			this.DefaultHeight = 221;
			this.Show ();
			this.ComboBoxTournamentType.Changed += new global::System.EventHandler (this.ComboBoxTournamentType_SelectionChanged);
			this.RadioButtonNoCut.Pressed += new global::System.EventHandler (this.RadioButtonPressed);
			this.TextboxName.Changed += new global::System.EventHandler (this.TextboxName_TextChanged);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.Cancel_Click);
			this.ButtonOK.Clicked += new global::System.EventHandler (this.NewTournament_Click);
		}
	}
}
