
// This file has been generated by the GUI designer. Do not modify.
namespace TXM.Lin
{
	public partial class OutputDialog
	{
		private global::Gtk.VBox vbox7;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView textblockOutput;
		
		private global::Gtk.HBox hbox14;
		
		private global::Gtk.Button button534;
		
		private global::Gtk.Button button533;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TXM.Lin.OutputDialog
			this.Name = "TXM.Lin.OutputDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("OutputDialog");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child TXM.Lin.OutputDialog.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textblockOutput = new global::Gtk.TextView ();
			this.textblockOutput.Sensitive = false;
			this.textblockOutput.CanFocus = true;
			this.textblockOutput.Name = "textblockOutput";
			this.GtkScrolledWindow.Add (this.textblockOutput);
			this.vbox7.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox ();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.button534 = new global::Gtk.Button ();
			this.button534.CanFocus = true;
			this.button534.Name = "button534";
			this.button534.UseUnderline = true;
			this.button534.Label = global::Mono.Unix.Catalog.GetString ("Kopieren");
			this.hbox14.Add (this.button534);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.button534]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.button533 = new global::Gtk.Button ();
			this.button533.CanFocus = true;
			this.button533.Name = "button533";
			this.button533.UseUnderline = true;
			this.button533.Label = global::Mono.Unix.Catalog.GetString ("Schließen");
			this.hbox14.Add (this.button533);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.button533]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox7.Add (this.hbox14);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox14]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.Add (this.vbox7);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 710;
			this.DefaultHeight = 567;
			this.Show ();
			this.button534.Clicked += new global::System.EventHandler (this.Button_Click_1);
			this.button533.Clicked += new global::System.EventHandler (this.Button_Click);
		}
	}
}
