
// This file has been generated by the GUI designer. Do not modify.
namespace TXM.Lin
{
	public partial class NewPlayerDialog
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Entry TextBoxNickname;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Entry TextBoxName;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Entry TextBoxForename;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Entry TextBoxTeam;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.ComboBox ComboBoxFaction;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.SpinButton IntegerUpDownSquadPoints;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.CheckButton CheckboxPayed;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.CheckButton CheckboxSquadListGiven;
		
		private global::Gtk.CheckButton CheckboxFreeticket;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.SpinButton IntegerUpDownStartNr;
		
		private global::Gtk.HBox hbox11;
		
		private global::Gtk.Label label16;
		
		private global::Gtk.Label labelWarning;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TXM.Lin.NewPlayerDialog
			this.Name = "TXM.Lin.NewPlayerDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child TXM.Lin.NewPlayerDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Nickname*");
			this.vbox4.Add (this.label10);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label10]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("(oder T3-Name)");
			this.vbox4.Add (this.label11);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label11]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.hbox1.Add (this.vbox4);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox4]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.TextBoxNickname = new global::Gtk.Entry ();
			this.TextBoxNickname.CanFocus = true;
			this.TextBoxNickname.Name = "TextBoxNickname";
			this.TextBoxNickname.IsEditable = true;
			this.TextBoxNickname.InvisibleChar = '●';
			this.hbox1.Add (this.TextBoxNickname);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.TextBoxNickname]));
			w5.Position = 1;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Name");
			this.hbox2.Add (this.label4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label4]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.TextBoxName = new global::Gtk.Entry ();
			this.TextBoxName.CanFocus = true;
			this.TextBoxName.Name = "TextBoxName";
			this.TextBoxName.IsEditable = true;
			this.TextBoxName.InvisibleChar = '●';
			this.hbox2.Add (this.TextBoxName);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.TextBoxName]));
			w8.Position = 1;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Vorname");
			this.hbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label2]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.TextBoxForename = new global::Gtk.Entry ();
			this.TextBoxForename.CanFocus = true;
			this.TextBoxForename.Name = "TextBoxForename";
			this.TextBoxForename.IsEditable = true;
			this.TextBoxForename.InvisibleChar = '●';
			this.hbox4.Add (this.TextBoxForename);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.TextBoxForename]));
			w11.Position = 0;
			this.hbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hbox4]));
			w12.Position = 1;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Team");
			this.hbox5.Add (this.label5);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label5]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.TextBoxTeam = new global::Gtk.Entry ();
			this.TextBoxTeam.CanFocus = true;
			this.TextBoxTeam.Name = "TextBoxTeam";
			this.TextBoxTeam.IsEditable = true;
			this.TextBoxTeam.InvisibleChar = '●';
			this.hbox5.Add (this.TextBoxTeam);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.TextBoxTeam]));
			w15.Position = 1;
			this.vbox2.Add (this.hbox5);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
			w16.Position = 3;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Fraktion*");
			this.hbox6.Add (this.label6);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label6]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.ComboBoxFaction = global::Gtk.ComboBox.NewText ();
			this.ComboBoxFaction.Name = "ComboBoxFaction";
			this.hbox6.Add (this.ComboBoxFaction);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.ComboBoxFaction]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox2.Add (this.hbox6);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox6]));
			w19.Position = 4;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Punktzahl (Squad)*");
			this.hbox7.Add (this.label7);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label7]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.IntegerUpDownSquadPoints = new global::Gtk.SpinButton (0, 1000, 1);
			this.IntegerUpDownSquadPoints.CanFocus = true;
			this.IntegerUpDownSquadPoints.Name = "IntegerUpDownSquadPoints";
			this.IntegerUpDownSquadPoints.Adjustment.PageIncrement = 10;
			this.IntegerUpDownSquadPoints.ClimbRate = 1;
			this.IntegerUpDownSquadPoints.Numeric = true;
			this.IntegerUpDownSquadPoints.Value = 100;
			this.hbox7.Add (this.IntegerUpDownSquadPoints);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.IntegerUpDownSquadPoints]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox2.Add (this.hbox7);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox7]));
			w22.Position = 5;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.CheckboxPayed = new global::Gtk.CheckButton ();
			this.CheckboxPayed.CanFocus = true;
			this.CheckboxPayed.Name = "CheckboxPayed";
			this.CheckboxPayed.Label = global::Mono.Unix.Catalog.GetString ("Bezahlt");
			this.CheckboxPayed.DrawIndicator = true;
			this.CheckboxPayed.UseUnderline = true;
			this.hbox8.Add (this.CheckboxPayed);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.CheckboxPayed]));
			w23.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.CheckboxSquadListGiven = new global::Gtk.CheckButton ();
			this.CheckboxSquadListGiven.CanFocus = true;
			this.CheckboxSquadListGiven.Name = "CheckboxSquadListGiven";
			this.CheckboxSquadListGiven.Label = global::Mono.Unix.Catalog.GetString ("Squadliste abgegeben");
			this.CheckboxSquadListGiven.DrawIndicator = true;
			this.CheckboxSquadListGiven.UseUnderline = true;
			this.vbox3.Add (this.CheckboxSquadListGiven);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.CheckboxSquadListGiven]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.CheckboxFreeticket = new global::Gtk.CheckButton ();
			this.CheckboxFreeticket.CanFocus = true;
			this.CheckboxFreeticket.Name = "CheckboxFreeticket";
			this.CheckboxFreeticket.Label = global::Mono.Unix.Catalog.GetString ("Gewonnenes Freilos");
			this.CheckboxFreeticket.DrawIndicator = true;
			this.CheckboxFreeticket.UseUnderline = true;
			this.vbox3.Add (this.CheckboxFreeticket);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.CheckboxFreeticket]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.hbox8.Add (this.vbox3);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.vbox3]));
			w26.Position = 1;
			this.vbox2.Add (this.hbox8);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox8]));
			w27.Position = 6;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Sensitive = false;
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Start-Nr");
			this.vbox5.Add (this.label12);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label12]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Sensitive = false;
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("(Wird automatisch");
			this.vbox5.Add (this.label13);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label13]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Sensitive = false;
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("hochgezählt, wenn leer)");
			this.vbox5.Add (this.label14);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label14]));
			w30.Position = 2;
			w30.Expand = false;
			w30.Fill = false;
			this.hbox9.Add (this.vbox5);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.vbox5]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.IntegerUpDownStartNr = new global::Gtk.SpinButton (0, 100, 1);
			this.IntegerUpDownStartNr.Sensitive = false;
			this.IntegerUpDownStartNr.CanFocus = true;
			this.IntegerUpDownStartNr.Name = "IntegerUpDownStartNr";
			this.IntegerUpDownStartNr.Adjustment.PageIncrement = 10;
			this.IntegerUpDownStartNr.ClimbRate = 1;
			this.IntegerUpDownStartNr.Numeric = true;
			this.hbox9.Add (this.IntegerUpDownStartNr);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.IntegerUpDownStartNr]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			this.vbox2.Add (this.hbox9);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox9]));
			w33.Position = 7;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("*=Pflichtfelder");
			this.hbox11.Add (this.label16);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label16]));
			w34.Position = 0;
			w34.Expand = false;
			w34.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.labelWarning = new global::Gtk.Label ();
			this.labelWarning.Name = "labelWarning";
			this.hbox11.Add (this.labelWarning);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.labelWarning]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			this.vbox2.Add (this.hbox11);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox11]));
			w36.Position = 8;
			w36.Expand = false;
			w36.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w37.Position = 0;
			w37.Expand = false;
			w37.Fill = false;
			// Internal child TXM.Lin.NewPlayerDialog.ActionArea
			global::Gtk.HButtonBox w38 = this.ActionArea;
			w38.Name = "dialog1_ActionArea";
			w38.Spacing = 10;
			w38.BorderWidth = ((uint)(5));
			w38.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w39 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w38 [this.buttonCancel]));
			w39.Expand = false;
			w39.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w40 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w38 [this.buttonOk]));
			w40.Position = 1;
			w40.Expand = false;
			w40.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 320;
			this.DefaultHeight = 461;
			this.Show ();
			this.TextBoxName.Changed += new global::System.EventHandler (this.ValueChanged);
			this.TextBoxForename.Changed += new global::System.EventHandler (this.ValueChanged);
			this.TextBoxTeam.Changed += new global::System.EventHandler (this.ValueChanged);
			this.ComboBoxFaction.Changed += new global::System.EventHandler (this.ValueChanged);
			this.IntegerUpDownSquadPoints.Changed += new global::System.EventHandler (this.IntegerUpDownSquadPoints_ValueChanged);
			this.CheckboxPayed.Pressed += new global::System.EventHandler (this.ValueChanged);
			this.CheckboxSquadListGiven.Pressed += new global::System.EventHandler (this.ValueChanged);
			this.CheckboxFreeticket.Pressed += new global::System.EventHandler (this.ValueChanged);
			this.buttonOk.Clicked += new global::System.EventHandler (this.NewPlayer_click);
		}
	}
}
