
// This file has been generated by the GUI designer. Do not modify.
namespace TXM.Lin
{
	public partial class SetPairingDialog
	{
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.HBox hbox13;
		
		private global::Gtk.ComboBox ComboboxPlayer1;
		
		private global::Gtk.ComboBox ComboboxPlayer2;
		
		private global::Gtk.Button ButtonAdd;
		
		private global::Gtk.Button buttonSub;
		
		private global::Gtk.Label label18;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.NodeView ListboxPairings;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TXM.Lin.SetPairingDialog
			this.Name = "TXM.Lin.SetPairingDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child TXM.Lin.SetPairingDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.ComboboxPlayer1 = global::Gtk.ComboBox.NewText ();
			this.ComboboxPlayer1.Name = "ComboboxPlayer1";
			this.hbox13.Add (this.ComboboxPlayer1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.ComboboxPlayer1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.ComboboxPlayer2 = global::Gtk.ComboBox.NewText ();
			this.ComboboxPlayer2.Name = "ComboboxPlayer2";
			this.hbox13.Add (this.ComboboxPlayer2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.ComboboxPlayer2]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.ButtonAdd = new global::Gtk.Button ();
			this.ButtonAdd.CanFocus = true;
			this.ButtonAdd.Name = "ButtonAdd";
			this.ButtonAdd.UseUnderline = true;
			this.ButtonAdd.Label = global::Mono.Unix.Catalog.GetString ("+");
			this.hbox13.Add (this.ButtonAdd);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.ButtonAdd]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.buttonSub = new global::Gtk.Button ();
			this.buttonSub.Sensitive = false;
			this.buttonSub.CanFocus = true;
			this.buttonSub.Name = "buttonSub";
			this.buttonSub.UseUnderline = true;
			this.buttonSub.Label = global::Mono.Unix.Catalog.GetString ("-");
			this.hbox13.Add (this.buttonSub);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.buttonSub]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox6.Add (this.hbox13);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox13]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Paarungen:");
			this.vbox6.Add (this.label18);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label18]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ListboxPairings = new global::Gtk.NodeView ();
			this.ListboxPairings.CanFocus = true;
			this.ListboxPairings.Name = "ListboxPairings";
			this.GtkScrolledWindow.Add (this.ListboxPairings);
			this.vbox6.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.GtkScrolledWindow]));
			w9.Position = 2;
			w1.Add (this.vbox6);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox6]));
			w10.Position = 0;
			// Internal child TXM.Lin.SetPairingDialog.ActionArea
			global::Gtk.HButtonBox w11 = this.ActionArea;
			w11.Name = "dialog1_ActionArea";
			w11.Spacing = 10;
			w11.BorderWidth = ((uint)(5));
			w11.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w11 [this.buttonCancel]));
			w12.Expand = false;
			w12.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w11 [this.buttonOk]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.ComboboxPlayer1.Changed += new global::System.EventHandler (this.Player1_SelectionChanged);
			this.ComboboxPlayer2.Changed += new global::System.EventHandler (this.Player2_SelectionChanged);
			this.ButtonAdd.Clicked += new global::System.EventHandler (this.ButtonAdd_Click);
			this.buttonSub.Clicked += new global::System.EventHandler (this.ButtonSub_Click);
			this.ListboxPairings.CursorChanged += new global::System.EventHandler (this.LbPairing_Changed);
			this.buttonOk.Clicked += new global::System.EventHandler (this.ButtonOK_Click);
		}
	}
}
